### ISSUE TITLE
在 Linux 格式化＆重命名隨身碟 | 郭桓桓的小站

### ISSUE THREAD

**Issue by kuohuanhuan** [kuohuanhuan/utility-room#8]
https://blog.nekohuan.cyou/2021/06/24/formatdisk/ 

 Hexo Theme Keep

**Comment by GrassBlock1** [comment]
您不是Arch用户吗（（（

**Comment by kuohuanhuan** [comment]
> @GrassBlock1
> 您不是Arch用户吗（（（

Windows -> Zorin OS -> Ubuntu -> Arch（失敗）-> Debian -> Manjaro -> Arch
